[package]
name = "easeprobe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1.83"
clap = { version = "4.5.23", features = ["derive"] }
log = "0.4.22"
logforth = "0.19.1"
once_cell = "1.20.2"
scopeguard = "1.2.0"
tokio = { version = "1", features = ["full"] }
